
    export DDKITSWEBPORT="${DDKITSWEBPORT}"
    export DDKITSDBPORT="${DDKITSDBPORT}"
    export DDKITSJENKINSPORT="${DDKITSJENKINSPORT}"
    export DDKITSSOLRPORT="${DDKITSSOLRPORT}"
    export DDKITSADMINPORT="${DDKITSADMINPORT}"
    export DDKITSREDISPORT="${DDKITSREDISPORT}"
      
