name: Deploy DDKits CLI documentation

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Correct action for GitHub Pages setup
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # If your site needs to be built, add the build step here
      # e.g. yarn install && yarn build
      # Remove this comment if no build step is needed.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './styleguide'   # Make sure this folder contains final static output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
